name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Flutter Web App
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # or whatever version you use

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web App
        run: flutter build web

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build/web"
          output_location: ""
