name: Build Flutter APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Build APK
        run: flutter build apk --release
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          file: build/app/outputs/flutter-apk/app-release.apk
          groups: testers
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk


